[package]
name = "mammut"
version = "0.9.1"
description = "A wrapper around the Mastodon API."
authors = ["Aaron Power <theaaronepower@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/Aaronepower/mammut.git"
keywords = ["api", "web", "social", "mastodon", "wrapper"]
categories = ["web-programming", "http-client"]

[dependencies]
reqwest = "0.8"
serde = "1"
serde_json = "1"
serde_derive = "1"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dev-dependencies]
dotenv = "0.10"
