[package]
name = "mammut"
version = "0.5.1"
description = "A wrapper around the Mastodon API."
authors = ["Aaron Power <theaaronepower@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/Aaronepower/mammut.git"
keywords = ["api", "web", "social", "mastodon", "wrapper"]
categories = ["web-programming", "http-client"]

[dependencies]
reqwest = "0.5"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"

[dependencies.chrono]
version = "0.3"
features = ["serde"]
